# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='JobPositions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024, verbose_name='Организация')),
                ('description', models.TextField(verbose_name='Описание')),
                ('month_from', models.PositiveSmallIntegerField()),
                ('month_to', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('year_from', models.PositiveIntegerField()),
                ('year_to', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
