# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_indexpage_jobpositions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobpositions',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='jobpositions',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
