# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20161006_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.BooleanField(default=False, verbose_name='Опубликовать'),
        ),
    ]
